alias l='ls -CF'
alias ls='ls -GF'
alias ll='ls -alF'
alias la='ls -AF'
alias mv='mv -i'
alias cp='cp -i'
alias diff='diff --strip-trailing-cr'
alias less='less -R'
alias update_develop='git fetch upstream develop && git merge upstream/develop'
alias run_front='yarn && NODE_OPTIONS="--max-old-space-size=8192" DISABLE_FORK_TS_CHECKER_WEBPACK_PLUGIN=1 DISABLE_UNUSED_FILES_WEBPACK_PLUGIN=1 XWEBPACK_ENTRIES="application,settings" yarn watch'
